changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '- {{ .Body -}}'
footerFormat: |
  {{- $azureBoardsFixed :=  customs .Changes "azure-boards-workitemid-fixed" | compact | uniq   }}
  {{ $azureBoardsRelated :=  customs .Changes "azure-boards-workitemid-related" | compact | uniq   }}
  {{ $GitHubLinks :=  customs .Changes "github-link" | compact | uniq   }}
  {{ $GitHubContributors :=  customs .Changes "github-contributor" | compact | uniq -}}
  ### Related
  {{ range $azureBoardsFixed }}
  - fixes AB#{{.}}
  {{- end -}}

  {{ range $azureBoardsRelated }}
  - related AB#{{.}}
  {{- end -}}

  {{ range $GitHubLinks }}
  - <{{.}}>
  {{- end }}
  {{ with $GitHubContributors }}
  ### Contributors
  {{ range $GitHubContributors }}
  - [{{.}}](https://github.com/{{.}})
  {{ end }}
  {{ end }}
kinds:
  - label: 🤖 CI & Build
    auto: patch
  - label: 🎉 New Product Feature
    auto: minor
  - label: ⬇️ Deprecated
    auto: minor
  - label: 🧪 Tests
    auto: patch
  - label: 🔨 Refactor
    auto: patch
  - label: 🐛 Bug Fix
    auto: patch
  - label: 🔥 Breaking Change
    auto: minor
  - label: 🔒 Security
    auto: patch
  - label: ⬆️ Dependencies
    auto: patch
  - label: 🔥 Major Version Change (Breaking Changes)
    auto: major
newlines:
  afterChange: 0
  afterChangelogHeader: 1
  afterChangelogVersion: 1
  afterComponent: 1
  afterFooterFile: 1
  afterFooter: 1
  afterHeaderFile: 1
  afterHeaderTemplate: 1
  afterKind: 1
  afterVersion: 1

  beforeChange: 0
  beforeChangelogVersion: 0
  beforeComponent: 0
  beforeFooterFile: 0
  beforeFooterTemplate: 0
  beforeHeaderFile: 0
  beforeHeaderTemplate: 0
  beforeKind: 0
  beforeVersion: 0
  endOfVersion: 0

custom:
  - key: github-contributor
    type: string
    minLength: 3
    optional: true
  - key: github-link
    label: GitHub Link
    type: string
    minLength: 3
    optional: true
  - key: azure-boards-workitemid-fixed
    label: FIXED Azure Boards WorkItem ID
    type: int
    minLength: 6
    optional: true
  - key: azure-boards-workitemid-related
    label: Related Azure Boards WorkItem ID
    type: int
    minLength: 6
    optional: true
replacements:
  # chart versions align with the release and get bumped by changie for us on `changie merge`.
  - path: 'dsv/package.json'
    find: '  "version": ".*",'
    replace: '  "version": "{{.VersionNoPrefix}}",'
  - path: dsv/task.json
    find: '    "Major": .*,'
    replace: '    "Major": {{.Major}},'
  - path: dsv/task.json
    find: '    "Minor": .*,'
    replace: '    "Minor": {{.Minor}},'
  - path: dsv/task.json
    find: '    "Patch": .*'
    replace: '    "Patch": {{.Patch}}'
