---
name: test
on:
  pull_request:
  # push:
  # branches:
  #   - main
  # tags:
  #   - v*
  workflow_dispatch:
  workflow_call:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      # https://github.com/magnetikonline/action-golang-cache
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@797f193169d3c8ba6f60d90f50ecdadd2583fbd8 # tag=v3
        with:
          go-version-file: go.mod

      - name: mage-tidy
        uses: magefile/mage-action@2c1951143e54356ebe6a0c6c971bae325b5b50f1 # tag=v2
        with:
          version: latest
          args: go:tidy

      - name: mage-test
        uses: magefile/mage-action@2c1951143e54356ebe6a0c6c971bae325b5b50f1 # tag=v2
        with:
          version: latest
          args: go:testsum ./...
        env:
          # Race conditions will be hit due to the cli driven tasks and binaries being called.
          GOTEST_DISABLE_RACE: 1
